//! Cross-implementation golden vectors.
//!
//! The fixtures in `../../tests/golden-vectors.json` are generated by
//! `scripts/generate-golden-vectors.mjs`, which runs the EXACT crypto code
//! path used by the browser extension (hash-wasm Argon2id + identical
//! rendering routines). Every entry must round-trip through the Rust
//! implementation to the same expected password. **A mismatch means the
//! Rust port has silently drifted from the extension — fail the build.**

use std::fs;
use std::path::Path;

use serde::Deserialize;

use keyfount_lib::crypto::{derive_password, fingerprint_master};
use keyfount_lib::types::{DerivationInputs, Profile};

#[derive(Debug, Deserialize)]
struct GoldenFile {
    cases: Vec<GoldenCase>,
    fingerprints: Vec<FingerprintCase>,
}

#[derive(Debug, Deserialize)]
struct GoldenCase {
    label: String,
    inputs: GoldenInputs,
    profile: Profile,
    expected_password: String,
}

#[derive(Debug, Deserialize)]
struct GoldenInputs {
    master: String,
    domain: String,
    email: String,
}

#[derive(Debug, Deserialize)]
struct FingerprintCase {
    master: String,
    expected_bytes: [u8; 3],
}

fn load_golden() -> GoldenFile {
    // The Cargo manifest dir is `src-tauri/`; the fixtures live one level up.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let path = Path::new(manifest_dir)
        .parent()
        .expect("manifest dir must have a parent")
        .join("tests")
        .join("golden-vectors.json");
    let raw = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "could not read golden vectors at {}: {e}\n\
             Run `node scripts/generate-golden-vectors.mjs` from the repo root.",
            path.display(),
        )
    });
    serde_json::from_str(&raw).expect("golden-vectors.json is not valid JSON")
}

#[tokio::test(flavor = "multi_thread")]
async fn every_golden_case_matches() {
    let golden = load_golden();
    let mut failures: Vec<String> = Vec::new();

    for case in &golden.cases {
        let inputs = DerivationInputs {
            master: case.inputs.master.clone(),
            domain: case.inputs.domain.clone(),
            email: case.inputs.email.clone(),
        };
        let got = derive_password(&inputs, &case.profile)
            .await
            .unwrap_or_else(|e| panic!("derive {} failed: {e:?}", case.label));
        if got != case.expected_password {
            failures.push(format!(
                "case {}: expected {:?}, got {:?}",
                case.label, case.expected_password, got
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} golden vector(s) mismatched:\n{}",
        failures.len(),
        failures.join("\n"),
    );
}

#[tokio::test(flavor = "multi_thread")]
async fn every_fingerprint_matches() {
    let golden = load_golden();
    let mut failures: Vec<String> = Vec::new();
    for case in &golden.fingerprints {
        let got = fingerprint_master(&case.master)
            .unwrap_or_else(|e| panic!("fingerprint {:?} failed: {e:?}", case.master));
        if got != case.expected_bytes {
            failures.push(format!(
                "fingerprint({:?}): expected {:?}, got {:?}",
                case.master, case.expected_bytes, got,
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} fingerprint(s) mismatched:\n{}",
        failures.len(),
        failures.join("\n"),
    );
}
